---
- hosts: all
  
  tasks:
  - name: Install vim
    ansible.builtin.package:
      name: vim
      state: present


# ansible all -i inventory -m service -a "name=firewalld state=stopped enabled=false" -k