---
collections:
  - name: community.general
    version: ">=11.0.0"
    source: https://galaxy.ansible.com

  - name: ansible.posix
    version: ">=2.0.0"
    source: https://galaxy.ansible.com